apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
spec:
  rules:
    - host: blog.140-110-136-74.nip.io
      http:
        paths:
          - backend:
              serviceName: wordpress-svc
              servicePort: 7070
