apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  selector:
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: alpine
    image: alpine
    command: 
    - sh
    - -c
    - |
      apk update
      apk add curl
      sleep 10000
