apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels:
    app: blog
    tier: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:php7.4
      imagePullPolicy: IfNotPresent
      env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
  nodeSelector:
    kubernetes.io/hostname: slave
